name: Deploy to Coolify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Coolify
        uses: coolifyhq/deploy-action@v1
        with:
          app-name: youtube-transcript-ui
          git-url: ${{ secrets.COOLIFY_GIT_URL }}
          git-token: ${{ secrets.COOLIFY_GIT_TOKEN }}
          environment: production
          branch: main
